global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
- mcp-rules.yml
scrape_configs:
- job_name: mcp-server
  static_configs:
  - targets:
    - localhost:3000
  metrics_path: /metrics
  scrape_interval: 5s
- job_name: node-exporter
  static_configs:
  - targets:
    - localhost:9100
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
