blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-org/ai-filesystem-mcp/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://ai-filesystem-mcp.dev
    about: Read the official documentation and guides
  - name: 🔒 Security Report
    url: https://github.com/your-org/ai-filesystem-mcp/security/advisories/new
    about: Report security vulnerabilities (private)
  - name: 💡 Feature Requests
    url: https://github.com/your-org/ai-filesystem-mcp/discussions/categories/ideas
    about: Suggest new features and enhancements
  - name: ❓ Support
    url: https://github.com/your-org/ai-filesystem-mcp/discussions/categories/q-a
    about: Get help with installation and usage